services:
  db:
    image: postgis/postgis:15-3.3
    container_name: safespot_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - safespot_network
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: safespot_redis
    restart: always
    networks:
      - safespot_network
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: safespot_web
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - safespot_network

  celery:
    build: .
    container_name: safespot_celery
    restart: always
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - safespot_network

volumes:
  postgres_data:
  static_volume:

networks:
  safespot_network:
    external: true
